server {
    listen 80;
    listen [::]:80;
    server_name baragao.magistertech.com.br;

    root /var/www/baragao.magistertech.com.br;
    index index.html;

    access_log /var/log/nginx/baragao_access.log;
    error_log  /var/log/nginx/baragao_error.log;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # Cache Control para assets estáticos
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|webp)$ {
        expires 30d;
        add_header Cache-Control "public, no-transform";
    }

    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;
}
